services:
  postgres:
    image: "postgres:latest"
    container_name: grand-capital-postgres
    environment:
      - POSTGRES_DB=grand-capital
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - "5432:5432"
    volumes:
      - grand-capital-postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: grand-capital-redis
    ports:
      - "6379:6379"
    volumes:
      - grand-capital-redis:/var/lib/redis/data

volumes:
  grand-capital-postgres:
  grand-capital-redis:
